---
version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
      - echo "Deploying..."
      - ls -l
      - aws --region eu-west-2 deploy create-deployment --application booksAppDeploy --deployment-group-name booksDeployGroup --s3-location bucket=books-pipeline,bundleType=YAML,key=appspec.yaml

