---
version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
      - echo Building...
      - env GO111MODULE=auto GOOS=linux GOARCH=amd64 go build -o ./main
      - zip -j ./main.zip ./main
artifacts:
  files:
    - main.zip
  name: main.zip
